export const AUTH = {
    LOGIN: 'AUTH.LOGIN',
    LOGIN_SUCCESS: 'AUTH.LOGIN_SUCCESS',
    LOGIN_ERROR: 'AUTH.LOGIN_ERROR',
    LOGOUT: 'AUTH.LOGOUT',
    LOGOUT_SUCCESS: 'AUTH.LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'AUTH.LOGOUT_ERROR',
    SIGNUP: 'AUTH.SIGNUP',
    SIGNUP_SUCCESS: 'AUTH.SIGNUP_SUCCESS',
    SIGNUP_ERROR: 'AUTH.SIGNUP_ERROR',
    HYDRATE: 'AUTH.HYDRATE',
}