export const HOME = {
    GET_PROJECTS: 'HOME.GET_PROJECTS',
    GET_PROJECTS_SUCCESS: 'HOME.GET_PROJECTS_SUCCESS',
    GET_PROJECTS_ERROR: 'HOME.GET_PROJECTS_ERROR',
    HYDRATE: 'HOME.HYDRATE',
}

export const PROJECT ={
    GET_PROJECT: 'PROJECT.GET_PROJECT',
    GET_PROJECT_SUCCESS: 'PROJECT.GET_PROJECT_SUCCESS',
    GET_PROJECT_ERROR: 'PROJECT.GET_PROJECT_ERROR',
    CREATE_PROJECT: 'PROJECT.CREATE_PROJECT',
    CREATE_PROJECT_SUCCESS: 'PROJECT.CREATE_PROJECT_SUCCESS',
    CREATE_PROJECT_ERROR: 'HOME.CREATE_PROJECT_ERROR',
    DELETE_PROJECT: 'PROJECT.DELETE_PROJECT',
    DELETE_PROJECT_SUCCESS: 'PROJECT.DELETE_PROJECT_SUCCESS',
    DELETE_PROJECT_ERROR: 'PROJECT.DELETE_PROJECT_ERROR',
}